[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = true
solc_version = "0.8.24"
evm_version = "cancun"

[profile.intense.fuzz]
max_test_rejects = 999999
runs = 10000

[rpc_endpoints]
sepolia = "https://ethereum-sepolia.publicnode.com"
goerli = "https://ethereum-goerli.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
